<?php
/**
 * Vidi Veda - Dynamic SEO Meta-Tag Injector
 */

// 1. Get the current request path (clean URL routing)
$request_uri = $_SERVER['REQUEST_URI'] ?? '/';
$path = parse_url($request_uri, PHP_URL_PATH);
$path = rtrim($path, '/');

// If root path is empty, default to '/'
if (empty($path)) {
    $path = '/';
}

// 2. Define default Fallback SEO Meta Tags
$title = "Vidi Veda | Trusted Home Tutors for CBSE & ICSE Across India";
$description = "Find verified personal home tutors and online tuition classes for CBSE & ICSE school students. One-to-one attention, experienced teachers, and better grades.";
$keywords = "home tutor, online tuition, CBSE home tutor, ICSE home tutor, Vidi Veda, personal tuition Bareilly, home tuition Meerut";

// 3. Load dynamic SEO configs from JSON database
$seo_json_file = __DIR__ . '/seoData.json';
if (file_exists($seo_json_file)) {
    $seo_data = json_decode(file_get_contents($seo_json_file), true);
    
    // Check if the current route has custom SEO tags
    if (is_array($seo_data) && isset($seo_data[$path])) {
        $title = $seo_data[$path]['title'] ?? $title;
        $description = $seo_data[$path]['description'] ?? $description;
        $keywords = $seo_data[$path]['keywords'] ?? $keywords;
    }
}

// 4. Fetch the compiled index.html generated by Vite build
$html_file = __DIR__ . '/index.html';

if (file_exists($html_file)) {
    $html = file_get_contents($html_file);
    
    // Inject dynamic tags into index.html
    $html = str_replace('{{META_TITLE}}', htmlspecialchars($title), $html);
    $html = str_replace('{{META_DESCRIPTION}}', htmlspecialchars($description), $html);
    $html = str_replace('{{META_KEYWORDS}}', htmlspecialchars($keywords), $html);
    
    echo $html;
} else {
    // If the site hasn't been built yet or index.html is missing
    header('Content-Type: text/html; charset=utf-8');
    echo "<!DOCTYPE html><html><head><title>Vidi Veda loading...</title></head><body style='font-family:sans-serif;text-align:center;padding:50px;'><h1>Vidi Veda Website is Loading...</h1><p>If you are the developer, run <code>npm run build</code> first to generate the production index.html file.</p></body></html>";
}
?>
